package UI;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

import Helpers_Renderers.WindowHelper;

public class GradePage {
    JPanel mainPanel;
    private JPanel GPANowPanel;
    private JPanel simulationPanel;
    private JLabel Header1;
    private JLabel currenGPAX;
    private JLabel totalCredits;
    private JTextField currenGPAX_txt;
    private JTextField totalCredits_txt;
    private JLabel header2;
    private JTable simulationTable;
    private JPanel buttom;
    private JButton calculateSave_button;
    private JButton removeCourse_button;
    private JButton back_button;
    private JButton addCourse_button;
    private JLabel totalGPAX;

    public GradePage() {
        //สร้างตาราง
        String[] columns = {"Subject", "Credits", "Target Grade"};
        DefaultTableModel model = new DefaultTableModel(null, columns);
        simulationTable.setModel(model);

        //ตกแต่งตาราง
        simulationTable.setRowHeight(50);
        simulationTable.getTableHeader().setBackground(new Color(43, 130, 212));
        simulationTable.getTableHeader().setForeground(Color.WHITE);
        simulationTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        simulationTable.getTableHeader().setPreferredSize(new Dimension(100, 45));
        simulationTable.setGridColor(new Color(220, 230, 240));
        simulationTable.setFont(new Font("Segoe UI", Font.PLAIN, 15));
        simulationTable.setSelectionBackground(new Color(175, 215, 250));

        back_button.addActionListener(e -> {
            try {
                WindowHelper.switchWindow(back_button, new MainPage().MainPage, "Study Management System");
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });

        addCourse_button.addActionListener(e -> {
            String subject = JOptionPane.showInputDialog("Subject Name:");
            if (subject == null || subject.trim().isEmpty()) return;

            int credits = Integer.parseInt(JOptionPane.showInputDialog("Credit:"));
            if (credits <= 0) return;

            String grade = JOptionPane.showInputDialog("Expected Grade:");
            if (grade == null || grade.trim().isEmpty()) return;

            model.addRow(new Object[]{subject, credits, grade}); //ลงตาราง
        });

        removeCourse_button.addActionListener(e -> {
            String target = JOptionPane.showInputDialog("Subject Name:");
            if (target != null && !target.trim().isEmpty()) {
                boolean found = false;
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (model.getValueAt(i, 0).toString().equalsIgnoreCase(target)) {
                        model.removeRow(i);
                        found = true;
                        break;
                    }
                }
                if (!found) JOptionPane.showMessageDialog(null, "Invalid Subject Name");
            }
        });

        calculateSave_button.addActionListener(e -> {
            try {
                double curG = Double.parseDouble(currenGPAX_txt.getText());
                int curC = Integer.parseInt(totalCredits_txt.getText());
                double totalPoints = curG * curC;
                int totalCredits = curC;

                for (int i = 0; i < model.getRowCount(); i++) {
                    int c = Integer.parseInt(model.getValueAt(i, 1).toString());
                    double g = convertGradeToPoint(model.getValueAt(i, 2).toString());
                    totalPoints += (g * c);
                    totalCredits += c;
                }
                totalGPAX.setText(String.format("Total GPAX: %.2f", (totalPoints / totalCredits)));
                JOptionPane.showMessageDialog(null, "GPAX calculated and saved successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Please enter valid numbers.",
                        "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    private double convertGradeToPoint(String grade) {
        switch (grade.toUpperCase().trim()) {
            case "A":
                return 4.0;
            case "B+":
                return 3.5;
            case "B":
                return 3.0;
            case "C+":
                return 2.5;
            case "C":
                return 2.0;
            case "D+":
                return 1.5;
            case "D":
                return 1.0;
            default:
                return 0.0;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-1));
        GPANowPanel = new JPanel();
        GPANowPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 5, new Insets(0, 0, 0, 0), -1, -1));
        GPANowPanel.setBackground(new Color(-656641));
        mainPanel.add(GPANowPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        Header1 = new JLabel();
        Header1.setBackground(new Color(-1));
        Font Header1Font = this.$$$getFont$$$("Tahoma", Font.BOLD, 16, Header1.getFont());
        if (Header1Font != null) Header1.setFont(Header1Font);
        Header1.setForeground(new Color(-13487566));
        Header1.setText("Cumulative Information (Current GPAX)");
        GPANowPanel.add(Header1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 5, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        currenGPAX = new JLabel();
        currenGPAX.setBackground(new Color(-656641));
        Font currenGPAXFont = this.$$$getFont$$$("Tahoma", -1, 14, currenGPAX.getFont());
        if (currenGPAXFont != null) currenGPAX.setFont(currenGPAXFont);
        currenGPAX.setForeground(new Color(-16777216));
        currenGPAX.setText("Current Cumulative GPAX:");
        GPANowPanel.add(currenGPAX, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        totalCredits = new JLabel();
        totalCredits.setBackground(new Color(-656641));
        Font totalCreditsFont = this.$$$getFont$$$("Tahoma", -1, 14, totalCredits.getFont());
        if (totalCreditsFont != null) totalCredits.setFont(totalCreditsFont);
        totalCredits.setForeground(new Color(-16777216));
        totalCredits.setText("Total Cumulative Credits");
        GPANowPanel.add(totalCredits, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        totalCredits_txt = new JTextField();
        GPANowPanel.add(totalCredits_txt, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 40), null, 0, false));
        currenGPAX_txt = new JTextField();
        GPANowPanel.add(currenGPAX_txt, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 40), null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        GPANowPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(1, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        GPANowPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(1, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        simulationPanel = new JPanel();
        simulationPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        simulationPanel.setBackground(new Color(-1));
        mainPanel.add(simulationPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        header2 = new JLabel();
        Font header2Font = this.$$$getFont$$$("Tahoma", Font.BOLD, 16, header2.getFont());
        if (header2Font != null) header2.setFont(header2Font);
        header2.setForeground(new Color(-13487566));
        header2.setText("Simulated Courses for This Semester");
        simulationPanel.add(header2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        simulationTable = new JTable();
        simulationPanel.add(simulationTable, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        buttom = new JPanel();
        buttom.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 4, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(buttom, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        calculateSave_button = new JButton();
        calculateSave_button.setBackground(new Color(-13925676));
        Font calculateSave_buttonFont = this.$$$getFont$$$("Tahoma", Font.BOLD, 18, calculateSave_button.getFont());
        if (calculateSave_buttonFont != null) calculateSave_button.setFont(calculateSave_buttonFont);
        calculateSave_button.setForeground(new Color(-1));
        calculateSave_button.setText("Calculate / Save");
        buttom.add(calculateSave_button, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 50), null, 0, false));
        removeCourse_button = new JButton();
        removeCourse_button.setBackground(new Color(-1618884));
        Font removeCourse_buttonFont = this.$$$getFont$$$("Tahoma", Font.BOLD, 18, removeCourse_button.getFont());
        if (removeCourse_buttonFont != null) removeCourse_button.setFont(removeCourse_buttonFont);
        removeCourse_button.setForeground(new Color(-1));
        removeCourse_button.setText("Remove Course");
        buttom.add(removeCourse_button, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 50), null, 0, false));
        addCourse_button = new JButton();
        addCourse_button.setBackground(new Color(-13925676));
        Font addCourse_buttonFont = this.$$$getFont$$$("Tahoma", Font.BOLD, 18, addCourse_button.getFont());
        if (addCourse_buttonFont != null) addCourse_button.setFont(addCourse_buttonFont);
        addCourse_button.setForeground(new Color(-1));
        addCourse_button.setText("Add Course");
        buttom.add(addCourse_button, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 50), null, 0, false));
        back_button = new JButton();
        back_button.setBackground(new Color(-13925676));
        Font back_buttonFont = this.$$$getFont$$$("Tahoma", Font.BOLD, 18, back_button.getFont());
        if (back_buttonFont != null) back_button.setFont(back_buttonFont);
        back_button.setForeground(new Color(-1));
        back_button.setText("Back");
        buttom.add(back_button, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 50), null, 0, false));
        totalGPAX = new JLabel();
        Font totalGPAXFont = this.$$$getFont$$$("Tahoma", Font.BOLD, 28, totalGPAX.getFont());
        if (totalGPAXFont != null) totalGPAX.setFont(totalGPAXFont);
        totalGPAX.setForeground(new Color(-15108398));
        totalGPAX.setText("Total GPAX: X.XX");
        mainPanel.add(totalGPAX, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}